USE customer_behaviour;

-- 1. What is the total revenue generated by MALE vs. FEMALE Customers?

SELECT gender, SUM(purchase_amount) as total_revenue
FROM customer 
GROUP BY gender;

-- 2. Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id, purchase_amount 
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount >=  (SELECT AVG(purchase_amount) FROM customer);

-- 3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased AS "Product",ROUND(AVG(review_rating),2) AS "Average Product Review"
FROM customer
GROUP BY item_purchased 
ORDER BY AVG(review_rating) DESC
LIMIT 5;
-- 4. Compare the average purchase_amount between Standard and Express Shipping?

SELECT shipping_type AS "Shipping", ROUND(AVG(purchase_amount),2) AS "Average Purchase Amount"
FROM customer
WHERE shipping_type = "Standard" OR shipping_type = "Express"
GROUP BY shipping_type;

-- 5. Do Subscribed customers spend more? Commare average spend and total revenue between subscribers and non-subscribers.

SELECT subscription_status, COUNT(customer_id) AS "Total Customers", 
ROUND(SUM(purchase_amount),2) AS "Total Revenue", 
ROUND(AVG(purchase_amount),2) AS "Average Purchase Amount"
FROM customer
GROUP BY subscription_status
ORDER BY "Total Revenue","Average Purchase Amount";

-- 6. Which 5 products have the highest percentage of purchases with discount applied?


SELECT 
    item_purchased,
    ROUND(
        SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 
        / COUNT(*), 
        2
    ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- 7. Segment customers into  New, Returning and Loyal based on
-- their total number of previous purchases, and show the count of each segment.

WITH customer_type  AS 
(
SELECT customer_id, previous_purchases,
CASE
WHEN previous_purchases = 1 THEN "New"
WHEN previous_purchases BETWEEN 2 AND 10 THEN "Returning"
ELSE "Loyal"
END AS customer_segment
FROM customer
)
SELECT customer_segment, COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;

-- 8. What are the top 3 most purchased products in each category?

WITH item_counts AS 
(
SELECT category, item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer
GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

-- 9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status; 

-- 10. What is the revenue contribution of the each age group?

SELECT age_group, SUM(purchase_amount) as total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;